{{- if .Values.agent.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "obsidianstack.fullname" . }}-agent-secrets
  namespace: {{ include "obsidianstack.namespace" . }}
  labels:
    {{- include "obsidianstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
type: Opaque
stringData:
  {{- range $k, $v := .Values.agent.secrets }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
