apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "obsidianstack.fullname" . }}-agent-config
  namespace: {{ include "obsidianstack.namespace" . }}
  labels:
    {{- include "obsidianstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
data:
  agent.yaml: |
    {{- .Values.agent.config | nindent 4 }}
