apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "obsidianstack.fullname" . }}-server-config
  namespace: {{ include "obsidianstack.namespace" . }}
  labels:
    {{- include "obsidianstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
data:
  server.yaml: |
    server:
    {{- .Values.server.config | nindent 6 }}
